# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# work around temporary travis + R 3.5 bug
r_packages: devtools

env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

install:
  - R -e 'install.packages(c("h2o", "xgboost"))'

before_install:
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov()'
